[build]
  # Skip build command since we're deploying pre-built files
  command = "echo 'Skipping build step...'"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-install"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
